name: "Sample SynthRad Configurations"
description: "Example configurations demonstrating different SynthRad features and capabilities"
metadata:
  version: "1.0"
  author: "SynthRad Team"
  created: "2024-01-01"

configurations:
  - name: "baseline_standard"
    description: "Standard baseline generation with balanced stage distribution"
    output_dir: "./out/baseline_standard"
    num_patients: 5
    seed: 42
    tags: ["baseline", "standard"]

  - name: "baseline_early_stage"
    description: "Early stage focused baseline generation"
    output_dir: "./out/baseline_early_stage"
    num_patients: 10
    seed: 42
    stage_distribution: "I:0.6,II:0.3,III:0.1,IV:0.0"
    tags: ["baseline", "early-stage"]

  - name: "baseline_advanced_stage"
    description: "Advanced stage focused baseline generation"
    output_dir: "./out/baseline_advanced_stage"
    num_patients: 10
    seed: 42
    stage_distribution: "I:0.0,II:0.1,III:0.4,IV:0.5"
    tags: ["baseline", "advanced-stage"]

  - name: "followup_standard"
    description: "Standard follow-up generation with response tracking"
    output_dir: "./out/followup_standard"
    num_patients: 5
    seed: 42
    follow_up: true
    studies_per_patient: 4
    tags: ["followup", "standard"]

  - name: "followup_optimistic"
    description: "Optimistic response follow-up with more positive outcomes"
    output_dir: "./out/followup_optimistic"
    num_patients: 5
    seed: 42
    follow_up: true
    studies_per_patient: 4
    response_distribution: "CR:0.2,PR:0.4,SD:0.3,PD:0.1"
    tags: ["followup", "optimistic"]

  - name: "followup_conservative"
    description: "Conservative response follow-up with more stable disease"
    output_dir: "./out/followup_conservative"
    num_patients: 5
    seed: 42
    follow_up: true
    studies_per_patient: 4
    response_distribution: "CR:0.05,PR:0.2,SD:0.5,PD:0.25"
    tags: ["followup", "conservative"]

  - name: "radlex_minimal"
    description: "Minimal RadLex terminology enhancement"
    output_dir: "./out/radlex_minimal"
    num_patients: 5
    seed: 42
    radlex_distribution: "minimal:1.0"
    tags: ["radlex", "minimal"]

  - name: "radlex_standard"
    description: "Standard RadLex terminology enhancement"
    output_dir: "./out/radlex_standard"
    num_patients: 5
    seed: 42
    radlex_distribution: "standard:1.0"
    tags: ["radlex", "standard"]

  - name: "radlex_aggressive"
    description: "Aggressive RadLex terminology enhancement"
    output_dir: "./out/radlex_aggressive"
    num_patients: 5
    seed: 42
    radlex_distribution: "aggressive:1.0"
    tags: ["radlex", "aggressive"]

  - name: "radlex_mixed"
    description: "Mixed RadLex enhancement levels"
    output_dir: "./out/radlex_mixed"
    num_patients: 5
    seed: 42
    radlex_distribution: "minimal:0.2,standard:0.5,aggressive:0.2,conservative:0.1"
    tags: ["radlex", "mixed"]

  - name: "jsonl_output"
    description: "Generate with JSONL output for React app integration"
    output_dir: "./out/jsonl_output"
    num_patients: 5
    seed: 42
    studies_per_patient: 4
    jsonl_filename: "cohort_labels.jsonl"
    tags: ["jsonl", "react"]

  - name: "custom_interval"
    description: "Generate with custom follow-up interval (60 days)"
    output_dir: "./out/custom_interval"
    num_patients: 5
    seed: 42
    follow_up: true
    follow_up_days: 60
    studies_per_patient: 4
    tags: ["followup", "custom-interval"]

  - name: "legacy_mode"
    description: "Generate using legacy file structure"
    output_dir: "./out/legacy_mode"
    num_patients: 5
    seed: 42
    legacy_mode: true
    follow_up: true
    tags: ["legacy"]
